[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
to_do_list = "E7YPSNL1RsHxBj8ByjcdnDbswfUDMYf8XMyby4kUDYxH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://staging-rpc.dev.eclipsenetwork.xyz"
wallet = "/Users/harshghodkar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
